# Generated by Django 3.1.7 on 2021-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('NEW', 'new'), ('SALE', 'sale'), ('GIFT', 'gift')], max_length=4, null=True),
        ),
    ]
