# Generated by Django 3.1.7 on 2021-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210328_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label_gift',
            field=models.CharField(blank=True, choices=[('NEW', 'new'), ('SALE', 'sale'), ('GIFT', 'gift')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='label_new',
            field=models.CharField(blank=True, choices=[('NEW', 'new'), ('SALE', 'sale'), ('GIFT', 'gift')], default='NEW', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='label_sale',
            field=models.CharField(blank=True, choices=[('NEW', 'new'), ('SALE', 'sale'), ('GIFT', 'gift')], max_length=4),
        ),
    ]
