# Generated by Django 3.1.7 on 2021-03-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210330_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parentcategory'),
            preserve_default=False,
        ),
    ]
